### ISSUE TITLE
participants video keeps loading 

### ISSUE THREAD

**Issue by vuppunaveen** [daily-co/react-native-daily-js#2]
<img width="293" alt="Screenshot 2020-11-05 at 3 28 27 PM" src="https://user-images.githubusercontent.com/28780160/98226152-aaaf8480-1f7b-11eb-8247-99faa36cb53a.png">

Hi team ,

Please help , participants video keeps loading  when we using create room privacy  set to 'private'

and creating meeting tokens with room name .

Url : https://subdomain.daily.co/roomname/?t=token

**Comment by filipi87** [comment]
Hi @vuppunaveen ,

Thanks for sharing this. Could you confirm if this bug is still happening?

In case yes, could you share with me:
- Version of Android or IOs;
- Logs from the simulator and from react-native;
- Version of the react-native-daily-js-playground that you are using.

It would be good if you could use the latest version of our playground app to validate: https://github.com/daily-co/react-native-daily-js-playground

**Comment by filipi87** [comment]
Closing the bug for inactivity. If the problem still happens, please open a new Issue sharing the informations that have been requested above.
We will be glad to help.
