### ISSUE TITLE
BUG: crash on iOS 13.2 simulator 

### ISSUE THREAD

**Issue by mike623** [daily-co/react-native-daily-js#20]
# Expected behavior
Application run without crash in playground application

# Describe the bug (unexpected behavior)
Application run  crash without providing error/ crash information 

# Steps to reproduce
1. `git clone https://github.com/daily-co/react-native-daily-js-playground.git`
2.  `npm i`
3.  `npm run ios -- --simulator="iPhone 11 (13.2)"`
4. click `create demo room`
5. wait room url filled
6. click `Join call`
7. wait at call panel screen
8. Simulator crashed

# Screenshots

![simulator_screenshot_61BB8D5E-A211-46AD-9DD8-E4678F70F478](https://user-images.githubusercontent.com/14008281/136570054-dc953780-3afb-4bb0-8cec-7b47f2a5fac1.png)

# System information 

 

* Device: iPhone iOS 13.2 simulator 
* OS, version: iOS 13.2
* Browser, version: 

# Additional context
• no crash at iOS 15.0 simulator by using same flow

**Comment by filipi87** [comment]
Hello @mike623 , thank you for sharing this issue with us. 

Could you share the logs ? Is this still happening for you with our latest playground application ?

**Comment by filipi87** [comment]
We have been able to simulate this issue here, and based on the logs, we found that this is actually a known issue on the iOS simulator. More info can be found here:
https://developer.apple.com/forums/thread/667921

Based on this, we are closing this issue, and recommend to use the latest version of the iOS when running on a simulator.

Let me know if you need any other help.
